const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const PORT=Number(process.env.PORT)||10000;
const BOT_TOKEN=process.env.BOT_TOKEN||process.env.TELEGRAM_BOT_TOKEN||'';
const OWNER_CHAT_ID=process.env.OWNER_CHAT_ID||'';
const send=(res,status,data)=>{const b=JSON.stringify(data);res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(b)};
const body=req=>new Promise((resolve,reject)=>{let b='',n=0;req.on('data',c=>{n+=c.length;if(n>65536){req.destroy();reject(Error('body too large'));return}b+=c});req.on('end',()=>resolve(b));req.on('error',reject)});
function valid(initData){if(!BOT_TOKEN||!initData)return {ok:false,reason:'Telegram authentication is not configured.'};const p=new URLSearchParams(initData),h=p.get('hash');if(!h)return {ok:false,reason:'Missing Telegram hash.'};p.delete('hash');const s=[...p.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>`${k}=${v}`).join('\n');const key=crypto.createHmac('sha256','WebAppData').update(BOT_TOKEN).digest();const calc=crypto.createHmac('sha256',key).update(s).digest('hex');const a=Buffer.from(calc,'hex'),b=Buffer.from(h,'hex');if(a.length!==b.length||!crypto.timingSafeEqual(a,b))return {ok:false,reason:'Invalid Telegram authentication.'};const age=Math.floor(Date.now()/1000)-Number(p.get('auth_date')||0);if(!Number.isFinite(age)||age<-60||age>86400)return {ok:false,reason:'Telegram session expired. Reopen the Mini App.'};let user={};try{if(p.get('user'))user=JSON.parse(p.get('user'))}catch{return {ok:false,reason:'Invalid Telegram user data.'}}return {ok:true,user}};
const clean=(v,max=40)=>String(v??'').replace(/[\u0000-\u001F\u007F]/g,'').trim().slice(0,max);
const modes=['love','bestfriend','fwb','sex','living','timepass','intimate'];
async function telegram(text){if(!BOT_TOKEN||!OWNER_CHAT_ID)throw Error('BOT_TOKEN or OWNER_CHAT_ID is not configured.');const r=await fetch(`https://api.telegram.org/bot${encodeURIComponent(BOT_TOKEN)}/sendMessage`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({chat_id:OWNER_CHAT_ID,text,disable_web_page_preview:true})});const d=await r.json().catch(()=>({}));if(!r.ok||!d.ok)throw Error(d.description||`Telegram API error ${r.status}`)}
async function submit(req,res){try{let p;try{p=JSON.parse(await body(req)||'{}')}catch{return send(res,400,{ok:false,error:'Invalid JSON.'})}const auth=valid(p.initData);if(!auth.ok)return send(res,401,{ok:false,error:auth.reason});const name=clean(p.name),their=clean(p.their_name),mode=clean(p.mode,20),score=Number(p.score);if(!name||!their)return send(res,400,{ok:false,error:'Both names are required.'});if(!modes.includes(mode))return send(res,400,{ok:false,error:'Invalid category.'});if(!Number.isInteger(score)||score<50||score>100)return send(res,400,{ok:false,error:'Invalid score.'});const u=auth.user||{},username=u.username?`@${u.username}`:'(no username)',id=u.id?String(u.id):'(unknown)';await telegram(`💘 MATCH METER RESULT\n\n👤 User: ${username}\n🆔 Telegram ID: ${id}\n\n❤️ Your name: ${name}\n💞 Their name: ${their}\n📊 Category: ${mode}\n🎯 Score: ${score}%`);send(res,200,{ok:true})}catch(e){console.error('POST /submit:',e);send(res,500,{ok:false,error:'Server could not submit the result.'})}}
http.createServer(async(req,res)=>{const u=new URL(req.url,`http://${req.headers.host||'localhost'}`);if(req.method==='GET'&&(u.pathname==='/'||u.pathname==='/index.html')){fs.readFile(path.join(__dirname,'index.html'),(e,d)=>{if(e)return send(res,500,{ok:false,error:'index.html is missing.'});res.writeHead(200,{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-cache'});res.end(d)});return}if(req.method==='GET'&&u.pathname==='/health')return send(res,200,{ok:true,service:'Match Meter V4',port:PORT,telegramConfigured:Boolean(BOT_TOKEN&&OWNER_CHAT_ID)});if(req.method==='POST'&&u.pathname==='/submit')return submit(req,res);res.writeHead(404,{'Content-Type':'text/plain'});res.end('Not found.')}).listen(PORT,'0.0.0.0',()=>console.log(`Match Meter V4 listening on ${PORT}`));
